#!/usr/bin/env bash

function log
{
    local LVL=$1
    local MSG=$2

    case $LVL in
        info) printf "\x1b[0;34m:: \x1b[39m$MSG\x1b[0m\n" >&2 ;;
        warn) printf "\x1b[1;33m:: \x1b[39m$MSG\x1b[0m\n" >&2 ;;
        err)  printf "\x1b[1;31m:: \x1b[39m$MSG\x1b[0m\n" >&2 ;;
        *)    printf "$MSG\n"                             >&2 ;;
    esac
}

function askyesno
{
    local MSG=$1

    printf "\x1b[1;32m?? \x1b[39m$MSG\x1b[0m " >&2
    read ANS && [ -z "$ANS" ] || [ "$ANS" == "y" ] || [ "$ANS" == "Y" ]
}

function run
{
    $@ >&2
}

function defaultsu
{
    su -c "$*"
}

CWD=$(cd -- $(dirname $0) && pwd)

# Get the distro
[ -r /etc/os-release ] && DISTRO=$(awk -F= '/^ID=/ {print $2}' /etc/os-release | xargs)

# Get the package manager if the distro is supported
case $DISTRO in
    arch)
        PMCMD="pacman --needed --sync"
        ;;
    gentoo)
        PMCMD="emerge --noreplace --ask --verbose"
        ;;
esac

# Get the command that will be used to run as root (fallback to su)
SUCMD=defaultsu
for CMD in doas sudo
do
    (command -v $CMD 2>&1 > /dev/null) && SUCMD=$CMD && break
done

# Check if a Gentoo overlay is enabled. Prompt user to enable it if it isn't.
function checkoverlay
{
    local OVERLAY=$1

    # Check if the overlay is enabled
    eselect repository list -i 2>&1 | grep --quiet "] $OVERLAY" && return 0

    log warn "The '$OVERLAY' overlay is required to install requested packages."
    askyesno "Would you like to enable it? [Y/n]" || return 1

    # Make sure the 'repository' eselect module is enabled
    if !(eselect modules list 2>&1 | grep --quiet "^  repository")
    then
        log warn "The 'repository' eselect module is not installed."

        askyesno "Would you like to install it? [Y/n]"                      &&
            run $SUCMD emerge --ask --verbose app-select/eselect-repository ||
            return 1
    fi

    # Enable and sync the requested overlay
    run $SUCMD eselect repository enable $OVERLAY || return 1
    run $SUCMD emaint sync -r $OVERLAY            || return 1
}

# Get the packages required by a given program for the distro.
function getpkgs
{
    local PROG=$1

    case "$PROG@$DISTRO" in
        zsh@arch)
            echo zsh zoxide fzf
            ;;
        zsh@gentoo)
            echo app-shells/{zsh,zoxide,fzf}
            ;;
        nvim@arch)
            echo neovim
            ;;
        nvim@gentoo)
            echo app-editors/neovim
            ;;
        hypr@arch)
            echo hyprland xdg-desktop-portal-hyprland
            ;;
        hypr@gentoo)
            checkoverlay hyproverlay && echo gui-wm/hyprland gui-libs/xdg-desktop-portal-hyprland
            ;;
        tmux@arch)
            echo tmux
            ;;
        tmux@gentoo)
            echo app-misc/tmux
            ;;
        fonts@arch)
            echo ttf-jetbrains-mono-nerd ttf-noto-nerd
            ;;
        fonts@gentoo)
            echo media-fonts/{jetbrains-mono,symbols-nerd-font,noto}
            ;;
        shextras@arch)
            echo lsd ripgrep fd bat
            ;;
        shextras@gentoo)
            echo sys-apps/{lsd,ripgrep,fd,bat}
            ;;
        *)
            log warn "No package preset for program '$PROG'."
            ;;
    esac
}

# Install the requested programs.
function installprogs
{
    if [ -z "$PMCMD" ]
    then
        log err "Cannot install packages on $DISTRO."
        return 1
    fi

    for PROG in $@
    do
        PKGS+="$(getpkgs $PROG) "
    done

    if (grep --quiet '\w' <<< $PKGS)
    then
        log info "The following packages and their dependencies will be installed:"
        for PKG in $PKGS
        do
            log info "  $PKG"
        done

        [ "$DISTRO" = "gentoo" ] && log info "Ensure desired USE flags have been set."

        askyesno "Continue [Y/n]" && $SUCMD $PMCMD $PKGS
    else
        log warn "No packages to be installed."
    fi
}

# Create a symlink for the provided program's config.
function linkconfig
{
    local CONF=${XDG_CONFIG_HOME:-$HOME/.config}
    local SRC=$1

    case $1 in
        zsh)
            DST=$CONF/zsh
            ;;
        nvim)
            DST=$CONF/nvim
            ;;
        hypr)
            DST=$CONF/hypr
            ;;
        tmux)
            DST=$CONF/tmux
            ;;
        extras/cleanhome/pythonrc)
            DST=$CONF/python/pythonrc
            ;;
        extras/cleanhome/npmrc)
            DST=$CONF/npm/npmrc
            ;;
        *)
            return
            ;;
    esac

    # TODO: Offer option to backup existing config instead of skipping if it already exists.

    if ! [ -e $DST ]
    then
        run mkdir --parents --verbose $(dirname $DST)
        run ln --symbolic --verbose $CWD/$SRC $DST
    else
        log warn "Not linking '$1' to '$DST' because a file already exists"
    fi
}

# Link the provided programs' configs.
function linkconfigs
{
    for PROG in $@
    do
        linkconfig $PROG
    done
}

function getallprogs
{
    echo zsh nvim hypr tmux fonts shextras
}

function linkcleanhome
{
    linkconfig extras/cleanhome/pythonrc
    linkconfig extras/cleanhome/npmrc
}

# TODO: More robust option parsing.
# TODO: Unlink config from backup.

case $1 in
    install)
        if [ $2 = all ] 
        then
            installprogs $(getallprogs)
        else
            installprogs ${@:2}
        fi
        ;;
    link)
        if [ $2 = all ]
        then
            linkconfigs $(getallprogs)
        else
            linkconfigs ${@:2}
        fi
        ;;
    keepcleanhome)
        linkcleanhome
        ;;
    everything)
        $CWD/setup install all       &&
            $CWD/setup link all      &&
            $CWD/setup keepcleanhome
        ;;
esac
