#!/usr/bin/env bash

CWD=$(cd -- $(dirname $0) && pwd)

if [ -r /etc/os-release ]
then
    DISTRO=$(awk -F= '/^ID=/ {print $2}' /etc/os-release | xargs)
else
    DISTRO=unknown
fi

for CMD in doas sudo
do
    if (command -v $CMD 2>&1 > /dev/null)
    then
        SU=$CMD
    fi
done

function log
{
    local LVL=$1
    local MSG=$2

    case $1 in
        info) printf "\x1b[1;34m:: \x1b[39m$MSG\x1b[0m\n"  >&2 ;;
        warn) printf "\x1b[1;33m:: \x1b[39m$MSG\x1b[0m\n"  >&2 ;;
        err)  printf "\x1b[1;31m:: \x1b[39m$MSG\x1b[0m\n"  >&2 ;;
        ask)  printf "\x1b[1;37m:: \x1b[39m$MSG\x1b[0m"    >&2 ;;
        *)    printf "$MSG\n"                              >&2 ;;
    esac
}

function checkoverlay
{
    if !(eselect repository list -i 2>&1 | grep --quiet "] $1")
    then
        log warn "The $1 overlay is not enabled!"
        log warn "To enable it, run:"
        log warn "  $SU eselect repository enable $1"
        log warn "  $SU emaint sync -r $1"
        echo
        return 1
    fi

    return 0
}

function getpkgs
{
    local PROG=$1

    case "$PROG@$DISTRO" in
        zsh@arch)
            echo zsh zoxide fzf
            ;;
        zsh@gentoo)
            echo app-shells/{zsh,zoxide,fzf}
            ;;
        nvim@arch)
            echo neovim
            ;;
        nvim@gentoo)
            echo app-editors/neovim
            ;;
        hypr@arch)
            echo hyprland xdg-desktop-portal-hyprland
            ;;
        hypr@gentoo)
            checkoverlay hyproverlay && echo gui-wm/hyprland gui-libs/xdg-desktop-portal-hyprland
            ;;
        tmux@arch)
            echo tmux
            ;;
        tmux@gentoo)
            echo app-misc/tmux
            ;;
        fonts@arch)
            echo ttf-jetbrains-mono-nerd ttf-noto-nerd
            ;;
        fonts@gentoo)
            echo media-fonts/{jetbrains-mono,symbols-nerd-font,noto}
            ;;
        extras@arch)
            echo lsd ripgrep fd bat
            ;;
        extras@gentoo)
            echo sys-apps/{lsd,ripgrep,fd,bat}
            ;;
        *)
            log warn "No package preset for program '$PROG' on $DISTRO"
            ;;
    esac
}

function installpkgs
{
    local PKGS=$@

    case $DISTRO in
        arch)
            $SU pacman --needed --sync $PKGS
            ;;
        gentoo)
            $SU emerge --noreplace --ask --verbose $PKGS
            ;;
        *)
            log err "Cannot install packages. ($DISTRO is not supported)"
            ;;
    esac
}

function installprogs
{
    if [ "$DISTRO" = "gentoo" ] && !(eselect modules list 2>&1 | grep --quiet '^  redpository')
    then
        log warn "The eselect 'repository' module is not installed."
        log warn "It might be needed to enable overlays for certain packages."
        log warn "Run '$SU emerge --ask --verbose app-select/eselect-repository' to install it."
        log info "Continuing..."
        echo
    fi

    for PROG in $@
    do
        PKGS+="$(getpkgs $PROG) "
    done

    if (echo $PKGS | grep --quiet '\w')
    then
        log info "The following packages will be installed:"
        for PKG in $PKGS
        do
            log info "  $PKG"
        done

        echo
        [ "$DISTRO" = "gentoo" ] && log info "Ensure desired USE flags have been set."
        log ask "Continue? (Control + C to cancel) "
        read || return 1

        installpkgs $PKGS
    fi
}

function linkconfig
{
    local CONF=${XDG_CONFIG_HOME:-$HOME/.config}
    local SRC=$1

    case $1 in
        zsh)
            DST=$CONF/zsh
            ;;
        nvim)
            DST=$CONF/nvim
            ;;
        hypr)
            DST=$CONF/hypr
            ;;
        tmux)
            DST=$CONF/tmux
            ;;
        extras/cleanhome/pythonrc)
            DST=$CONF/python/pythonrc
            ;;
        extras/cleanhome/npmrc)
            DST=$CONF/npm/npmrc
            ;;
        *)
            return
            ;;
    esac

    # TODO: Offer option to backup existing config instead of skipping if it already exists.

    if ! [ -e $DST ]
    then
        mkdir --parents --verbose $(dirname $DST)
        ln --symbolic --verbose $CWD/$SRC $DST
    else
        log warn "Not linking '$1' to '$DST' because a file already exists"
    fi
}

function linkconfigs
{
    for PROG in $@
    do
        linkconfig $PROG
    done
}

function getallprogs
{
    echo zsh nvim hypr tmux fonts extras
}

function linkcleanhome
{
    linkconfig extras/cleanhome/pythonrc
    linkconfig extras/cleanhome/npmrc
}

# TODO: More robust option parsing.
# TODO: Unlink config from backup.

case $1 in
    install)
        if [ $2 = all ] 
        then
            installprogs $(getallprogs)
        else
            installprogs ${@:2}
        fi
        ;;
    link)
        if [ $2 = all ]
        then
            linkconfigs $(getallprogs)
        else
            linkconfigs ${@:2}
        fi
        ;;
    keepcleanhome)
        linkcleanhome
        ;;
    everything)
        $CWD/setup install all
        $CWD/setup link all
        $CWD/setup keepcleanhome
        ;;
esac
