#!/usr/bin/env bash

CWD=$(cd -- $(dirname $0) && pwd)

function getdistro
{
    [ -r /etc/os-release ]                                     \
        && awk -F= '/^ID=/ {print $2}' /etc/os-release | xargs \
        || echo linux
}

function getsucmd
{
    for C in sudo doas ; do
        (command -v $C 2>&1 > /dev/null) \
            && echo $C && return
    done
}

function getaurhelper
{
    for C in paru yay aura ; do
        (command -v $C 2>&1 > /dev/null) \
            && echo $C && return
    done
}

function getpkgs
{
    local DISTRO=$1
    local PROG=$2

    case "$PROG@$DISTRO" in
        zsh@arch)
            echo zsh starship zoxide fzf
            ;;
        zsh@gentoo)
            echo app-shells/{zsh,starship,zoxide,fzf}
            ;;
        kitty@arch)
            echo kitty
            ;;
        kitty@gentoo)
            echo x11-terms/kitty
            ;;
        nvim@arch)
            echo neovim luarocks
            ;;
        nvim@gentoo)
            echo app-editors/neovim dev-lua/luarocks
            ;;
        hypr@arch)
            echo hyprland
            ;;
        hypr@gentoo)
            echo gui-wm/hyprland
            ;;
        tmux@arch)
            echo tmux
            ;;
        tmux@gentoo)
            echo app-misc/tmux
            ;;
        starship@arch)
            echo starship
            ;;
        starship@gentoo)
            echo app-shells/starship
            ;;
        fonts@arch)
            echo ttf-jetbrains-mono-nerd ttf-noto-nerd
            ;;
        fonts@gentoo)
            echo media-fonts/{jetbrains-mono-nerd,noto}
            ;;
        extras@arch)
            echo lsd ripgrep fd bat xdg-desktop-portal-hyprland
            ;;
        extras@gentoo)
            echo sys-apps/{lsd,ripgrep,fd,bat} gui-libs/xdg-desktop-portal-hyprland
            ;;
        *)
            echo "No package preset for program '$PROG' on $DISTRO" >&2
            ;;
    esac
}

function installpkgs
{
    local DISTRO=$1
    local PKGS=${@:2}
    local SU=$(getsucmd)

    case $DISTRO in
        arch)
            $(getaurhelper) --needed -S $PKGS
            ;;
        gentoo)
            $SU emerge --ask $PKGS
            ;;
        *)
            echo "Cannot install packages. ($DISTRO is not supported)" >&2
            ;;
    esac
}

function installprogs
{
    local DISTRO=$(getdistro)

    for PROG in $@ ; do
        PKGS+="$(getpkgs $DISTRO $PROG) "
    done

    [ ${#PKGS} -gt 0 ] && installpkgs $DISTRO $PKGS
}

function linkconfig
{
    local CONF=${XDG_CONFIG_HOME:-$HOME/.config}
    local SRC=$1

    case $1 in
        zsh)
            DST=$CONF/zsh
            ;;
        kitty)
            DST=$CONF/kitty
            ;;
        nvim)
            DST=$CONF/nvim
            ;;
        hypr)
            DST=$CONF/hypr
            ;;
        tmux)
            DST=$CONF/tmux
            ;;
        starship)
            SRC=starship.toml
            DST=$CONF/starship.toml
            ;;
        extras/cleanhome/pythonrc)
            DST=$CONF/python/pythonrc
            ;;
        extras/cleanhome/npmrc)
            DST=$CONF/npm/npmrc
            ;;
        *)
            return
            ;;
    esac

    if ! [ -e $DST ] ; then
        mkdir --parents --verbose $(dirname $DST)
        ln --symbolic --verbose $CWD/$SRC $DST
    else
        echo "Not linking '$1' to '$DST' because a file already exists"
    fi
}

function linkconfigs
{
    for PROG in $@ ; do
        linkconfig $PROG
    done
}

function getallprogs
{
    echo zsh kitty nvim hypr tmux starship fonts extras
}

function linkcleanhome
{
    linkconfig extras/cleanhome/pythonrc
    linkconfig extras/cleanhome/npmrc
}

case $1 in
    install)
        if [ $2 = all ] ; then
            installprogs $(getallprogs)
        else
            installprogs ${@:2}
        fi
        ;;
    link)
        if [ $2 = all ] ; then
            linkconfigs $(getallprogs)
        else
            linkconfigs ${@:2}
        fi
        ;;
    keepcleanhome)
        linkcleanhome
        ;;
    everything)
        $CWD/setup install all
        $CWD/setup link all
        $CWD/setup keepcleanhome
        ;;
esac
